#!/bin/sh
echo "> Installing maven"
wget apache.rediris.es/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
cd /module
tar -xzf apache-maven-3.3.3-bin.tar.gz -C /opt/sds
echo "export M2_HOME=/opt/sds/apache-maven-3.3.3" >> /home/vagrant/.bashrc
source ~/.bashrc
echo "export PATH=/opt/sds/apache-maven-3.3.3/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin" >> /home/vagrant/.bashrc

echo "> Starting MongoDB"
echo "smallfiles=true" >> /etc/mongod.conf
/sbin/service mongod start

echo "> Starting ElasticSearch"
/sbin/service elasticsearch start
echo "http.cors.enabled: true" >> /etc/sds/elasticsearch/elasticsearch.yml
/opt/sds/elasticsearch/bin/./plugin -install royrusso/elasticsearch-HQ
/opt/sds/elasticsearch/bin/./plugin -install mobz/elasticsearch-head

rm -f /etc/udev/rules.d/70-persistent-net.rules

echo "> Installing Crossdata"
/usr/bin/yum -y install stratio-crossdata
/sbin/chkconfig --add sparkta
/sbin/chkconfig  sparkta on
/sbin/chkconfig  zookeeper on
/sbin/chkconfig --list
service zookeeper start
service sparkta start

yum clean all
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY