#!/bin/sh
STRATIO_ENV=$1
STRATIO_MODULE="crossdata ova"
STRATIO_MODULE_VERSION="0.3.0-SNAPSHOT"
ipaddress=$(ip -4 addr show dev eth0 | grep inet | sed 's/^ *//g' | cut -d' ' -f 2 | cut -d'/' -f1)
#######################################
## SERVICES
#######################################
#######################################
## Cassandra
#######################################
echo "Installing Cassandra..."
rpm --quiet -q stratio-cassandra || yum -y -q --nogpgcheck install stratio-cassandra
echo "Configuring Cassandra..."
##Config Cassandra:
sed -i "s/^\(num_tokens:\)/#\1/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^# \(initial_token:\)/\1/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(hinted_handoff_enabled:\) true$/\1 false/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(concurrent_reads:\) 32$/\1 16/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(concurrent_writes:\) 32$/\1 8/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(concurrent_counter_writes:\) 32$/\1 16/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/\(seeds:\) \"127.0.0.1\"/\1 \"$ipaddress\"/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(listen_address:\).*$/\1 $ipaddress/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^\(rpc_address:\).*$/\1 0.0.0.0/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/^# \(broadcast_rpc_address:\).*$/\1 $ipaddress/" /etc/sds/cassandra/cassandra.yaml
sed -i "s/\(\-Dcassandra.logdir=\)\$CASSANDRA_HOME\/logs/\1\/var\/log\/sds\/cassandra/" /opt/sds/cassandra/bin/cassandra
#######################################
## Crossdata
#######################################
echo "Installing Crossdata..."
rpm --quiet -q jakarta-commons-daemon-jsvc || yum -y -q --nogpgcheck install http://$REPOSITORY/RHEL/6.5/x86_64/jakarta-commons-daemon-jsvc-1.0.1-8.9.el6.x86_64.rpm
rpm --quiet -q stratio-crossdata || yum -y -q --nogpgcheck install stratio-crossdata
echo "Configuring Crossdata..."
#Config Crossdata
sed -i "s/^\(CROSSDATA_HOME=\).*$/\1\"\/opt\/sds\/crossdata\"/" /etc/sds/crossdata/crossdata-env.sh
sed -i "s/^\(CROSSDATA_LOG_OUT=\).*$/\1\"\/var\/log\/sds\/crossdata\/crossdata-server.out\"/" /etc/sds/crossdata/crossdata-env.sh
sed -i "s/^\(CROSSDATA_LOG_ERR=\).*$/\1\"\/var\/log\/sds\/crossdata\/crossdata-server.err\"/" /etc/sds/crossdata/crossdata-env.sh
sed -i "s/^\(CROSSDATA_SERVER_PID=\).*$/\1\"\/var\/run\/sds\/crossdata-server.pid\"/" /etc/sds/crossdata/crossdata-env.sh
sed -i "s/^\(crossdata-server.akka.remote.netty.tcp.hostname =\).*$/\1 \"$ipaddress\"/" /etc/sds/crossdata/server-application.conf
sed -i "s/^\(crossdata-server.akka.cluster.seed-nodes =\).*$/\1 \[\"akka.tcp\:\/\/CrossdataServerCluster\@$ipaddress\:13420\"\]/" /etc/sds/crossdata/server-application.conf
sed -i "s/^\(crossdata-driver.config.cluster.hosts =\).*$/\1 \[\"$ipaddress\:13420\"\]/" /etc/sds/crossdata/driver-application.conf
#######################################
## Spark
#######################################
echo "Installing Spark..."
rpm --quiet -q stratio-spark || yum -y -q --nogpgcheck install stratio-spark
echo "Generating keys..."
mkdir /opt/sds/spark/.ssh
chmod 700 /opt/sds/spark/.ssh
ssh-keygen -t rsa -b 2048 -f /opt/sds/spark/.ssh/id_rsa -N ""
cp /opt/sds/spark/.ssh/id_rsa.pub /opt/sds/spark/.ssh/authorized_keys
chown -R spark:spark /opt/sds/spark/.ssh/
#Config Spark
echo "Configuring Spark..."
sed -i "s/^\(spark.master\).*$/\1 spark:\/\/$ipaddress:7077/" /etc/sds/spark/spark-defaults.conf
sed -i "s/^export MESOS_NATIVE_LIBRARY=.*$//" /etc/sds/spark/spark-env.sh
sed -i "s/^export MASTER=.*$//" /etc/sds/spark/spark-env.sh
sed -i "s/^#export SPARK_EXECUTOR_URI=.*$//" /etc/sds/spark/spark-env.sh
sed -i "s/\(SPARK_WORKER_MEMORY=\)\"4g\"/\1\"2g\"/" /etc/sds/spark/spark-env.sh
sed -i "s/\(SPARK_WORKER_CORES\)=2/\1=1/" /etc/sds/spark/spark-env.sh
sed -i "s/^#\(SPARK_MASTER_IP=\)/\1$ipaddress/" /etc/sds/spark/spark-env.sh
sed -i "s/^#\(SPARK_EXECUTOR_MEMORY=\)/\1/" /etc/sds/spark/spark-env.sh
sed -i "s/^#\(SPARK_DRIVER_MEMORY=\)/\1/" /etc/sds/spark/spark-env.sh
#######################################
## Connectors
#######################################
#Cassandra
echo "Installing Cassandra connector..."
rpm --quiet -q stratio-connector-cassandra || yum -y -q --nogpgcheck install stratio-connector-cassandra
#config
echo "Configuring Cassandra connector..."
sed -i "s/^\(crossdata-connector.akka.cluster.seed-nodes =\).*$/\1 \[\"akka.tcp\:\/\/CrossdataServerCluster\@$ipaddress\:13420\"\]/" /etc/sds/connectors/cassandra/connector-application.conf
sed -i "s/^\(crossdata-connector.akka.remote.netty.tcp.hostname =\).*$/\1 \"$ipaddress\"/" /etc/sds/connectors/cassandra/connector-application.conf
#Deep
echo "Installing Deep connector..."
rpm --quiet -q stratio-connector-deep || yum -y -q --nogpgcheck install stratio-connector-deep
#config
echo "Configuring Deep connector..."
sed -i "s/^\(crossdata-connector.akka.cluster.seed-nodes =\).*$/\1 \[\"akka.tcp\:\/\/CrossdataServerCluster\@$ipaddress\:13420\"\]/" /etc/sds/connectors/deep/connector-application.conf
sed -i "s/^\(crossdata-connector.akka.remote.netty.tcp.hostname =\).*$/\1 \"$ipaddress\"/" /etc/sds/connectors/deep/connector-application.conf
chkconfig --add crossdata
chkconfig --add cassandra
chkconfig --add connector_cassandra
chkconfig --add connector_deep
chkconfig crossdata off
chkconfig cassandra on
chkconfig connector_cassandra off
chkconfig connector_deep off
echo "Starting services..."
service cassandra start

cat >>/etc/rc.local <<EOF
if [ ! -f $LOCK_FILE ]; then
   curl -f -s -m 5 http://www.stratio.com/CheckUpdate/${STRATIO_MODULE}/${STRATIO_MODULE_VERSION}
   echo "ok" > ${LOCK_FILE}
fi
EOF

echo "Starting demo environment"
cat >>/home/vagrant/.bash_profile <<EOF 
echo "--- PLEASE READ /etc/sds/crossdata/README.txt ---" 
EOF
wget -P /etc/sds/crossdata https://github.com/miguel0afd/crossdata-client-example/raw/master/src/main/resources/README.txt --no-check-certificate
wget -P /etc/sds/crossdata https://github.com/miguel0afd/crossdata-client-example/raw/master/src/main/resources/CrossdataClientExample.jar --no-check-certificate
echo "Follow instructions in /etc/sds/crossdata/README.txt"
