CROSSBUILD:
  - '2.10'
  - '2.11'

ITSERVICES:
  - SPARK:
      image: stratio/spark:1.6.1
      env:
        - SPARK_MODE=master
  - ZOOKEEPER:
      image: stratio/zookeeper:3.4.6
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - SPARK:
      image: stratio/spark:1.6.1
      env:
        - SPARK_MODE=slave
        - SPARK_MASTER_HOST=%%SPARK#0
  - ELASTICSEARCH:
      image: stratio/elasticsearch:1.7.1
      sleep: 5
      env:
        - CLUSTER_NAME=%%JUID
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:2.2.5.3
      sleep: 10
      env:
        - MAX_HEAP=256M
  - HADOOP:
      image: stratio/hadoop:2.7.2
      env:
        - MASTER_NODE=true
  - KAFKA:
      image: stratio/kafka:0.8.2.1
      env:
        - ZOOKEEPER_HOSTS=%%ZOOKEEPER:2181

ITPARAMETERS: >
    -Dcassandra.hosts.0=%%CASSANDRA
    -Dmongo.hosts.0=%%MONGODB
    -Delasticsearch.hosts.0=%%ELASTICSEARCH
    -Delasticsearch.cluster=%%JUID
    -Dspark.master=spark://%%SPARK:7077
    -Dhdfs.namenode=hdfs://%%HADOOP:9000
    -Dcrossdata-core.hdfs.hdfsMaster=%%HADOOP
    -Dcatalog.zookeeper.connectionString=%%ZOOKEEPER:2181
    -Dstreaming.catalog.zookeeper.connectionString=%%ZOOKEEPER:2181
    -Dstreaming.receiver.kafka.connection=%%KAFKA:9092
    -Dstreaming.receiver.zookeeper.connectionString=%%ZOOKEEPER:2181
