#!/bin/bash -xe

CROSSDATA_DRIVER_CONFIG_HTTP_SERVER_HOST=$SHELL_SERVERADDR
CROSSDATA_DRIVER_CONFIG_HTTP_SERVER_PORT=$SHELL_SERVERPORT

# Prepare options string from docker environment settings

OPTIONS=""

if [ -n "$SHELL_USER" ]; then
    OPTIONS="$OPTIONS --user $SHELL_USER"
fi;

if [ "$CONNECTION_TIMEOUT" ]; then
    OPTIONS="$OPTIONS --timeout $CONNECTION_TIMEOUT"
fi;

OPTIONS="$OPTIONS --http"

if [ "$SHELL_MODE" == "async" ]; then
    OPTIONS="$OPTIONS --async"
fi;

if [ "$SHELL_CERTIFICATE_PATH" -a "$SHELL_CERTIFICATE_PASSWORD" -a "$SHELL_TRUSTSTORE_PATH" -a "$SHELL_TRUSTSTORE_PASSWORD" ]; then
    CROSSDATA_DRIVER_AKKA_HTTP_SSL_ENABLE="true"
    CROSSDATA_DRIVER_AKKA_HTTP_SSL_KEYSTORE=$SHELL_CERTIFICATE_PATH
    CROSSDATA_DRIVER_AKKA_HTTP_SSL_KEYSTORE_PASSWORD=$SHELL_CERTIFICATE_PASSWORD
    CROSSDATA_DRIVER_AKKA_HTTP_SSL_TRUSTSTORE=$SHELL_TRUSTSTORE_PATH
    CROSSDATA_DRIVER_AKKA_HTTP_SSL_TRUSTSTORE_PASSWORD=$SHELL_TRUSTSTORE_PASSWORD
fi