#!/bin/bash -xe

export CROSSDATA_DRIVER_CONFIG_HTTP_SERVER_HOST=$SHELL_SERVERADDR
export CROSSDATA_DRIVER_CONFIG_HTTP_SERVER_PORT=$SHELL_SERVERPORT

# Prepare options string from docker environment settings

export OPTIONS=""

if [ -n "$SHELL_USER" ]; then
    export OPTIONS="$OPTIONS --user $SHELL_USER"
fi;

if [ "$CONNECTION_TIMEOUT" ]; then
    export OPTIONS="$OPTIONS --timeout $CONNECTION_TIMEOUT"
fi;

export OPTIONS="$OPTIONS --http"

if [ "$SHELL_MODE" == "async" ]; then
    export OPTIONS="$OPTIONS --async"
fi;

if [ "$SHELL_CERTIFICATE_PATH" -a "$SHELL_CERTIFICATE_PASSWORD" -a "$SHELL_TRUSTSTORE_PATH" -a "$SHELL_TRUSTSTORE_PASSWORD" ]; then
    export CROSSDATA_DRIVER_AKKA_HTTP_SSL_ENABLE="true"
    export CROSSDATA_DRIVER_AKKA_HTTP_SSL_KEYSTORE=$SHELL_CERTIFICATE_PATH
    export CROSSDATA_DRIVER_AKKA_HTTP_SSL_KEYSTORE_PASSWORD=$SHELL_CERTIFICATE_PASSWORD
    export CROSSDATA_DRIVER_AKKA_HTTP_SSL_TRUSTSTORE=$SHELL_TRUSTSTORE_PATH
    export CROSSDATA_DRIVER_AKKA_HTTP_SSL_TRUSTSTORE_PASSWORD=$SHELL_TRUSTSTORE_PASSWORD
fi