//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 01:59:34 PM CEST 
//


package com.stratio.meta2.common.api.connector;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.stratio.meta2.common.api.Manifest;
import com.stratio.meta2.common.api.PropertiesType;

/**
 * <p>Java class for ConnectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConnectorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataStores" type="{}DataStoreRefsType"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequiredProperties" type="{}PropertiesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OptionalProperties" type="{}PropertiesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SupportedOperations" type="{}SupportedOperationsType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectorType", propOrder = {
    "connectorName",
    "dataStores",
    "version",
    "requiredProperties",
    "optionalProperties",
    "supportedOperations"
})
public class ConnectorType extends Manifest {

    @XmlElement(name = "ConnectorName", required = true)
    protected String connectorName;
    @XmlElement(name = "DataStores", required = true)
    protected DataStoreRefsType dataStores;
    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "RequiredProperties")
    protected List<PropertiesType> requiredProperties;
    @XmlElement(name = "OptionalProperties")
    protected List<PropertiesType> optionalProperties;
    @XmlElement(name = "SupportedOperations", required = true)
    protected List<SupportedOperationsType> supportedOperations;

    public ConnectorType() {
        super(Manifest.TYPE_CONNECTOR);
    }

    /**
     * Gets the value of the connectorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectorName() {
        return connectorName;
    }

    /**
     * Sets the value of the connectorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectorName(String value) {
        this.connectorName = value;
    }

    /**
     * Gets the value of the dataStores property.
     * 
     * @return
     *     possible object is
     *     {@link DataStoreRefsType }
     *     
     */
    public DataStoreRefsType getDataStores() {
        return dataStores;
    }

    /**
     * Sets the value of the dataStores property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataStoreRefsType }
     *     
     */
    public void setDataStores(DataStoreRefsType value) {
        this.dataStores = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the requiredProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiredProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertiesType }
     * 
     * 
     */
    public List<PropertiesType> getRequiredProperties() {
        if (requiredProperties == null) {
            requiredProperties = new ArrayList<PropertiesType>();
        }
        return this.requiredProperties;
    }

    /**
     * Gets the value of the optionalProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionalProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionalProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertiesType }
     * 
     * 
     */
    public List<PropertiesType> getOptionalProperties() {
        if (optionalProperties == null) {
            optionalProperties = new ArrayList<PropertiesType>();
        }
        return this.optionalProperties;
    }

    /**
     * Gets the value of the supportedOperations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedOperations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedOperations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportedOperationsType }
     * 
     * 
     */
    public List<SupportedOperationsType> getSupportedOperations() {
        if (supportedOperations == null) {
            supportedOperations = new ArrayList<SupportedOperationsType>();
        }
        return this.supportedOperations;
    }

}
