#!/bin/bash

export SPARK_HOME="$(cd `dirname $0`/..; pwd)"

xdjars="$SPARK_HOME/lib/crossdata-ng-1.0.0-SNAPSHOT.jar"

sparkArguments="$@"

if [[ "$@" = *"--cassandra"* ]]; then
	echo "Adding cassandra Jars"
   xdjars="$xdjars,$SPARK_HOME/lib/crossdata-cassandra-1.0.0-SNAPSHOT.jar"
   sparkArguments=${sparkArguments/--cassandra/}  
fi


$SPARK_HOME/bin/spark-shell -i $SPARK_HOME/bin/stratio-xd-init.scala --jars $xdjars $sparkArguments